# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=140)),
                ('region', models.CharField(max_length=140)),
                ('locality', models.CharField(max_length=140)),
                ('street', models.CharField(max_length=140)),
                ('number', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('nif', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=140)),
                ('activity', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react.Address')),
                ('childs', models.ManyToManyField(blank=True, related_name='_company_childs_+', to='react.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('max_subcompanies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SubContracts_child', to='react.Company')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SubContracts_parent', to='react.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('package', models.ManyToManyField(to='react.Package')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='subcontracts',
            unique_together=set([('parent', 'child')]),
        ),
    ]
